### ISSUE TITLE
Error during training:  Target contains only one unique value

### ISSUE THREAD

**Issue by davidbaines** [JEdward7777/SentenceTransmogrifier#1]
I tried running sentence transmogrifier with this command line below
I used a simple training set which consisted of English verses with and without spaces.
I've attached that file in case it is helpful for finding the problem. 

`python transmorgrify.py --train --in_csv E:\Work\Pilot_projects\Nuoso\transmog_train.txt --a_header original --b_header split --device 0:1  --model [nuoso_gpu_100.tm](http://nuoso_gpu_100.tm/)  --verbose --iterations 100 --train_percentage 30
`

The end of the trace looks like this:

```
97:     learn: 0.1640706        total: 1.94s    remaining: 39.6ms
98:     learn: 0.1636335        total: 1.96s    remaining: 19.8ms
99:     learn: 0.1629958        total: 1.98s    remaining: 0us
action is fitted: True
action params:
{'iterations': 100, 'learning_rate': 0.07, 'task_type': 'GPU', 'devices': '0:1'}
Traceback (most recent call last):
  File "F:\GitHub\SentenceTransmogrifier\transmorgrify.py", line 652, in <module>
    main()
  File "F:\GitHub\SentenceTransmogrifier\transmorgrify.py", line 611, in main
    train( in_csv=args.in_csv,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GitHub\SentenceTransmogrifier\transmorgrify.py", line 515, in train
    tm.train( from_sentences=train_data[a_header],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GitHub\SentenceTransmogrifier\transmorgrify.py", line 40, in train
    self.char_model = _train_catboost( X[insert_indexes], Y['char'][insert_indexes], iterations, verbose=verbose, device=device, model_piece='char' )
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\GitHub\SentenceTransmogrifier\transmorgrify.py", line 388, in _train_catboost
    model.fit( train_pool, eval_set=validation_pool, verbose=True )
  File "F:\GitHub\SentenceTransmogrifier\venv\Lib\site-packages\catboost\core.py", line 5100, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, sample_weight, None, None, None, None, baseline, use_best_model,
  File "F:\GitHub\SentenceTransmogrifier\venv\Lib\site-packages\catboost\core.py", line 2319, in _fit
    self._train(
  File "F:\GitHub\SentenceTransmogrifier\venv\Lib\site-packages\catboost\core.py", line 1723, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 4645, in _catboost._CatBoost._train
  File "_catboost.pyx", line 4694, in _catboost._CatBoost._train
_catboost.CatBoostError: C:/Go_Agent/pipelines/BuildMaster/catboost.git/catboost/private/libs/target/target_converter.cpp:375: Target contains only one unique value
```

[training_latin.txt](https://github.com/JEdward7777/SentenceTransmogrifier/files/13545801/training_latin.txt)

**Comment by JEdward7777** [comment]
Ok, I believe I know what is going on.  The system has two models,
 1, one what to do, a: drop, b: pass, c: insert
 2, what to insert.

When you are inserting just spaces, the model which is trained of what to insert has a constant output.  It always needs to insert a space, and it isn't happy about that.  So to get around this condition for now, add some more variation in the text besides needing to put the spaces back in.  Take out the periods as well or something like that.   Then the insertion model will have something for it to learn.  Period or space.

**Comment by JEdward7777** [comment]
I added the boundary case so that a second model is not trained if the output is constant.
